#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
    path: /{_locale}
    controller: App\Controller\DefaultController::homepage
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'
    
add_product:
    path: /{_locale}/add/product/
    controller: App\Controller\ProductController::addProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'
    
register_user:
    path: /{_locale}/register/user/
    controller: App\Controller\UserController::registerUser
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'

activate_user:
    path: /{_locale}/user/activate/{token}/
    controller: App\Controller\UserController::activateUser
    defaults:
        _locale: en
    requirements:
       token: '[a-z0-9-]+'
       _locale: 'en|fr'
       
list_product:
    path: /{_locale}/product/list/
    controller: App\Controller\ProductController::listProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'

detail_product:
    path: /{_locale}/product/detail/
    controller: App\Controller\ProductController::detailProduct
    defaults:
        _locale: en
    requirements:
        _locale: 'en|fr'
        

username_available:
    path: /username/available
    controller: App\Controller\UserController::usernameAvailable
    methods: ['POST']
    
login:
  path: /{_locale}/login/
  controller: App\Controller\UserController::login
    
logout:
 path: /logout
    
    
    
    
    
    